### ISSUE TITLE
Several issues (block breaking, chests)

### ISSUE THREAD

**Issue by CblaProf** [kitskub/MyHungerGames#40] opened 2013-03-23 12:34 UTC
1. Block breaking list bug, i want to let people to break leaves, and i can't, i have it like:
   can-break-block: false
   special-blocks-break
   - 18
   - 18:*
   - leaves

(tried every possible combination to the list, just leaves, just 18, etc., some other blocks are working, leaves no, i just get the message you are not allowed to break while in <arena>). Now if i set can-break-block to true, then it overwrittes the Essential Anti Build settings ...
1. Chests ... i want to leave the chests as they are, i have some survival game worlds set up, is there any possibility not to clear the chests? I have removed everything from item configs, but still, when i open a chest and i get lucky and it doesn't crash the server (issue #36) then the chests is empty.

Bukkit: 1.5.1 - R0.1
MyHungerGames: 0.9.2

Thanks.

**Comment by kitskub** [comment] 2013-03-24 04:57
Duplicate of bug report on BukkitDev

**Closed as completed by kitskub** 2013-03-24 04:57 UTC
